title: Barbería Elegance
email: contacto@barberiaelegance.com
description: Reserva tu turno de forma rápida y sencilla con los mejores barberos.
baseurl: "/losangelesbarber"
url: "https://losangelesbarberco.github.io"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - supabase_schema.sql
  - node_modules
  - README.md
